# Introduction

In Canada, data on Pacific salmon and steelhead are not readily accessible, synthesized in a centralized location, kept up to date, or used to assess biological or habitat status in a standardized way. In the absence of a common baseline understanding of the status of specific salmon and steelhead populations, it is difficult to make informed, transparent, and evidence-based management and conservation decisions. To address this challenge, the Pacific Salmon Foundation’s (PSF) [Salmon Watersheds Program](https://www.salmonwatersheds.ca) has been working since 2008 to improve access to timely information on the biological status of wild salmon and steelhead and pressures on their freshwater habitats through the Pacific Salmon Explorer, an interactive data visualization tool, and a Salmon Data Library. With these tools, we seek to improve access to information in a centralized location, visualize this information in an engaging and useful manner, and inform decision-making processes for salmon and steelhead conservation and management.

There are several reasons why we are leading this work. First, there is a lack of standardized, readily accessible information about salmon and steelhead and their freshwater habitats. For example, this work evolved from initial processes undertaken in the Skeena watershed, where a lack of understanding of the state of salmon and their habitats resulted in conflict among management agencies and user groups in regard to fisheries management challenges and potential solutions. Second, this lack of information makes it difficult to determine when and where management actions are needed to improve the status and abundance of salmon and steelhead populations. Third, limited resources and capacity often result in managers and decision-makers prioritizing where to invest limited resources in the conservation and management of Pacific salmon and steelhead. By understanding salmon and steelhead population status and potential threats to their freshwater habitats, people can better understand what actions might improve outcomes for salmon and steelhead and where those may be best applied. Providing timely and open-access information can inform strategic planning initiatives for salmon and steelhead. 
The overarching goal of this work is the democratization of information to support science-based conservation and management decisions for salmon and steelhead. The main objectives of this work are to: 

* Strengthen baseline scientific information for Pacific salmon and steelhead and their habitats,
* Provide timely and standardized assessments of biological status of wild Pacific salmon and steelhead and pressures on freshwater salmon and steelhead habitats in BC and the Yukon,
* Make information about Pacific salmon and steelhead and their habitats broadly accessible, and
* Support efforts to integrate this work into conservation, management, and strategic planning initiatives for salmon and steelhead in BC and the Yukon. 

To meet these objectives, the methods that we apply to assess biological and habitat statuses are consistent and transferrable across the Regions in the Pacific Salmon Explorer. Our overall approach is also intentionally iterative and incremental in that we seek and incorporate feedback and improvements to the analytical and communications work that we do. As such, any data that we include in the Pacific Salmon Explorer must be consistently collected, available at broad spatial scales, accompanied by detailed documentation, and allow for reproducibility of analyses (e.g. through code and automation). Finally, for this work to inform conservation, management, and strategic planning efforts, we continue to support and engage in social processes that improve awareness, application, and development of the Pacific Salmon Explorer.

Our efforts to assess biological and habitat status align with Canada’s Wild Salmon Policy (DFO, 2005), a science-based framework for monitoring wild Pacific salmon biodiversity across BC and the Yukon. The Wild Salmon Policy seeks to maintain salmon biodiversity through the protection of Conservation Units (CUs). A CU is defined in the Wild Salmon Policy as “a group of wild salmon sufficiently isolated from other groups that, if extirpated, is very unlikely to recolonize naturally within an acceptable time frame, such as a human lifetime or a specified number of salmon generations” (DFO, 2005). Fisheries and Oceans Canada (DFO) has defined over 400 CUs in BC and the Yukon based on similarities in their ecology, life history, and genetics (Holtby & Ciruna, 2007). Protecting CUs serves to protect the minimum level of biodiversity required to maintain the resilience of salmon populations.

The Wild Salmon Policy identified six strategies to apply to the conservation and management of salmon. Strategies 1 through 3 focus on improving the current understanding of salmon populations, habitats, and ecosystems through standardized assessment and monitoring. Strategies 4 through 6 focus on management and designing and implementing planning activities that use the baseline information gathered in Strategies 1-3 to manage, maintain, and rebuild salmon CUs and their habitats. The Wild Salmon Policy 2018-2022 Implementation Plan (DFO, 2018) proposed a path forward to implement these strategies. The Pacific Salmon Explorer is part of this implementation plan, understanding that the work of “maintaining and rebuilding salmon populations and their habitats” requires both DFO and effective partnerships. While steelhead were not formally included in the Wild Salmon Policy, the strategies within the policy, including monitoring biological and habitat status at a CU scale, are relevant and appropriate for steelhead, which share many similarities to Pacific salmon. 

Working in collaboration with First Nations, DFO, and others, we apply methods consistent with Strategies 1 and 2 of the Wild Salmon Policy to assess the biological and habitat status of salmon and steelhead CUs. We provide these assessments across Regions delineated by PSF according to watershed and CU boundaries. This technical report provides a detailed overview of our approach and analytical methodologies as a reference document for the Pacific Salmon Explorer. Up-to-date status assessments and data are accessible within this online tool. In the following sections of this report, we detail our general approach, the Regions of BC and Yukon within which we work, our analytical approach, and detailed Region-specific methodologies. We will update this report as data sources, methods, and approaches evolve.  
