# Conclusions and Future Directions {#conclusions}

By synthesizing and providing open access to information and standardized assessments of salmon biological status and pressures on freshwater habitats, the [Pacific Salmon Explorer](https://www.salmonexplorer.ca) can help inform and improve decision-making for the conservation and management of wild salmon. This information can help identify where to apply management interventions to support the recovery of at-risk populations and where more research and monitoring efforts are needed to assess threats to salmon habitat properly.

Determining which CUs are high priorities for management interventions and recovery planning is challenging. It requires both assumptions and acceptance of the inherent uncertainty in assessing biological status and habitat pressures. Acknowledging these challenges, we suggest prioritizing efforts under two scenarios. (1) CUs whose biological status is in the red status zone based on both PSF assessments and other integrated status assessments, and (2) CUs where biological status is data deficient and habitat risk level is red. However, given the numerous trade-offs and other factors to consider in conservation planning, we recommend that the Pacific Salmon Explorer outputs be considered part of a broader strategic planning approach. One that considers societal values, recovery potential, and the feasibility and cost of management and conservation actions. 

Compiling and synthesizing information all available data sources related to salmon and Salmon CUs serves to improve our understanding of wild salmon population status and the apparent reasons for a given status. Additional pressures affecting salmon that are not currently included on the Pacific Salmon Explorer should also be considered. For example, climate change-related indicators and indicators of marine productivity have important implications for the productivity and abundance of wild Pacific salmon. Given the iterative nature of our work, the current set of biological and habitat indicators are likely to evolve, and this technical report and its methodologies will be updated accordingly. 

PSF intends to continue working in collaboration with Fisheries and Oceans Canada, First Nations, and other salmon experts to regularly update the biological and habitat indicators used for assessments to ensure that the Pacific Salmon Explorer remains a comprehensive and trusted resource for informing decision making associated with salmon conservation, management, and recovery. 
