# Appendix 6: Habitat Pressure Datasets & Data Sources {#appendix-6 .unnumbered}

| Source                                               | Indicator    | Date of Data          | Date Accessed              |
|:-----------------------------------|:-----------|:-----------|:-----------|
| [Agriculture Land Dispositions](https://open.yukon.ca/data/datasets/agriculture-land-dispositions) (GeoYukon)                                                           | Agriculture                             | 2023-11-21                                          | 2024-02-21  |
| [Baseline Thematic Mapping](https://catalogue.data.gov.bc.ca/dataset/baseline-thematic-mapping-present-land-use-version-1-spatial-layer) (DataBC) | Agriculture                            | 1992                                            | 2024-02-18  |
| [VRI](https://catalogue.data.gov.bc.ca/dataset/vri-2023-forest-vegetation-composite-polygons) (DataBC)                  | Agriculture                            | 2023                                           | 2024-10-01  |
| [Historical Fire Polygons](https://catalogue.data.gov.bc.ca/dataset/bc-wildfire-fire-perimeters-historical) (DataBC)                                                           | Fire                             |2024-04-01                                          | 2024-02-08  |
| [Current Fire Polygons](https://catalogue.data.gov.bc.ca/dataset/bc-wildfire-fire-perimeters-current) (DataBC)                                                           | Fire                            | 2024-04-01                                        | 2024-09-30  |
| [Fire History](https://open.yukon.ca/data/datasets/fire-history) (DataBC)                                                           | Fire                            | 2023-04-01                                        | 2024-09-30  |
| [Burn Severity Polygons](https://catalogue.data.gov.bc.ca/dataset/fire-burn-severity-historical) (DataBC)                                                           | Fire                             | 2023-11-24                                          | 2024-02-10   |
| [Forest Inventory Zones](https://catalogue.data.gov.bc.ca/dataset/forest-inventory-zones) (DataBC)                                                           | Fire                             | 2018-03-30                                          | 2024-10-01  |
| [Harvested Areas in BC (Consolidated Cutblocks)](https://catalogue.data.gov.bc.ca/dataset/harvested-areas-of-bc-consolidated-cutblocks-) (DataBC)                                                           | Forest Harvest                             | 2023-10-24                                          | 2024-02-08  |
| [Results Inventory (for reserves)](https://catalogue.data.gov.bc.ca/dataset/results-forest-cover-inventory) (DataBC)                                                           | Forest Harvest                             | 2024-03-30                                          | 2024-03-30  |
| [Forest Disturbance in the Haida Gwaii Region](https://data.salmonwatersheds.ca/result?datasetid=444) (Gowgaia Institute)                                                | Forest Harvest                            | 2021                                          | 2021-11-09  |
| [Forest Openings](https://open.yukon.ca/data/datasets/forest-openings) (GeoYukon)                                                           | Forest Harvest                            | 2021-07-06                                          | 2023-09-06  |
| [Historic Silviculture Inventory 50K](https://open.yukon.ca/data/datasets/forest-openings) (GeoYukon)                                                           | Forest Harvest                            | 2001-01-02                                          | 2023-09-06  |
| [Pest Infestation Polygons](https://catalogue.data.gov.bc.ca/dataset/pest-infestation-polygons) (DataBC)                                                           | Insect Damage                             | 2022                                          | 2024-10-01  |
| [VRI Dead Layer](https://catalogue.data.gov.bc.ca/dataset/vri-2023-forest-vegetation-composite-dead-layer-d-) (DataBC)                                                           | Insect Damage                             | 2023                                          | 2024-10-01  |
| [Forest Health Overview](https://open.yukon.ca/data/datasets/forest-health-aerial-overview-50k) (GeoYukon)                                                           | Insect Damage                            | 2022                                          | 2024-03-04  |
| [Minfile Inventory Database](https://catalogue.data.gov.bc.ca/dataset/minfile-inventory-database) (DataBC)                                                           | Mines                            | 2024-02-12                                          | 2024-02-21  |
| [Minfile Production Database](https://catalogue.data.gov.bc.ca/dataset/minfile-production-database) (DataBC)                                                           | Mines                            | 2021                                          | 2024-02-21  |
| [BC Aggregate Inventory Private Pits (2004)](http://apps.empr.gov.bc.ca/pub/mapplace/mp2/fusion/templates/mapguide/slate/index.html?ApplicationDefinition=Library://mp2.ApplicationDefinition&locale=en&bcgovtm=20200319_GCPE_AM_COVID_4_NOTIFICATION_BCGOV_BCGOV_EN_BC__NOTIFICATION) (British Columbia Geological Survey MapPlace)                                                           | Mines                             | 2004                                          | 2012 |
| [Quartz Land Use Permits 50k](https://open.yukon.ca/data/datasets/quartz-land-use-permits-50k) (GeoYukon)                                                           | Mines                             | 2024-02-22                                         | 2024-04-06  |
| [Quartz Mining Licenses 50K](https://open.yukon.ca/data/datasets/quartz-mining-licences-50k) (GeoYukon)                                                           | Mines                             | 2013-09-20                                          | 2024-04-06  |
| [Quartz Leases 50K](https://open.yukon.ca/data/datasets/quartz-leases-50k) (GeoYukon)                                                           | Mines                             | 2012-08-27                                          | 2024-04-06  |
| [Mineral Claims Polygon Surveyed](https://open.yukon.ca/data/datasets/mineral-claims-polygon-surveyed) (GeoYukon)                                                           | Mines                             | 2017-04-24                                          | 2024-04-06  |
| [Coal Leases 50K](https://open.yukon.ca/data/datasets/coal-leases-50k) (GeoYukon)                                                           | Mines                             | 2017-04-18                                          | 2024-04-06  |
| [Coal Exploration Licenses 50K](https://open.yukon.ca/data/datasets/coal-exploration-licenses-50k) (GeoYukon)                                                           | Mines                             | 2022-11-23                                          | 2024-04-06  |
| [Gravel Pits 25K](https://open.yukon.ca/data/datasets/gravel-pits-25k) (GeoYukon)                                                           | Mines                             | 2023-09-16                                        | 2024-04-06  |
| [BC Cumulative Effects Framework Integrated Roads](https://catalogue.data.gov.bc.ca/dataset/bc-cumulative-effects-framework-integrated-roads-archived) (DataBC)                                                           | Roads                             | 2021                                         | 2023-09-06  |
| [Yukon Road Network](https://open.yukon.ca/data/datasets/yukon-road-network) (GeoYukon)                                                           | Roads                             | 2022-03-08                                         | 2023-09-12  |
| [Forestry Resource Roads 50K](https://open.yukon.ca/data/datasets/forestry-resource-roads-50k) (GeoYukon)                                                           | Roads                            | 2021-09-20                                          | 2023-09-12  |
| [BC Cumulative Effects Framework Human Disturbance](https://catalogue.data.gov.bc.ca/dataset/bc-cumulative-effects-framework-human-disturbance-archived) (DataBC)                                                           | Urban & Industrial Development                            | 2021                                          | 2023-09-06  |
| [Landcover circa 2000](https://open.canada.ca/data/en/dataset/97126362-5a85-4fe0-9dc2-915464cfdbb7) (Government of Canada)                                                           | Urban & Industrial Development                            | 2000s                                          | 2023-09-12  |
| [Utilities Line 50K](https://open.yukon.ca/data/datasets/utilities-line-50k) (GeoYukon)                                                           | Urban & Industrial Development                             | 2004-06-14                                         | 2023-09-12 |
| [YEC Power Lines](https://open.yukon.ca/data/datasets/yec-power-lines) (GeoYukon)                                                           | Urban & Industrial Development                             | 2021-01-13                                          | 2023-09-12 |
| [YEC Power Distribution Lines](https://open.yukon.ca/data/datasets/yec-power-distribution-lines) (GeoYukon)                                                           | Urban & Industrial Development                             | 2021-01-13                                          | 2023-09-12 |
| [Railroads 50K Canvec](https://open.yukon.ca/data/datasets/railroads-50k-canvec) (GeoYukon)                       | Urban & Industrial Development  | 2017 | 2023-09-12 |
| [Runways 25K](https://open.yukon.ca/data/datasets/runways-25k) (GeoYukon)                       | Urban & Industrial Development  | 2023-09-16 | 2023-09-12 |  


: (#tab:habDataSources) Sources of habitat pressure datasets used as inputs for habitat indicator assessments.