# Appendix 7: Spatial Data Processing for Habitat Indicators {#appendix-7 .unnumbered}

| Dataset Name                             | Filter                                                                                                 | Processing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Source                                      | Date of Data                          | Indicator      | Region(s)        | Date Accessed    |
|------------------------------------------|--------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|---------------------------------------|----------------|------------------|------------------|
| Agriculture Land Dispositions            | TENURE_PURPOSE = ‘Agricultural’ –> se type 7 <br> TENURE_PURPOSE = ‘Grazing’ –> se type 6              | Apply filters <br> Assign se_type codes to each filter <br> Union inputs <br> Calculate max_type_code <br> Dissolve on max_type_code <br> Reclassify max_type_code to populate datasource and type (Unknown, Unknown (clearing), Rangeland, Cropland) <br> Intersect with watersheds to calculate % watershed affected by agriculture = agricultural area/total watershed area                                                                                                                                                                                                                                                                                                                                                              | GeoYukon                                    | 2023-11-21                          | Agriculture    | Yukon            | 2024-02-21       |
| Baseline Thematic Mapping                | PLU_LABEL = ‘Agriculture’ –> se type 5 <br> PLU_LABEL = ‘Range Lands’ –> se type 4                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | 1992-03-31                          | Agriculture    | BC               | 2024-02-18       |
| VRI                                      | NON_PRODUCTIVE_DESCRIPTOR_CD = 'OR' –> se type 3 <br> NON_PRODUCTIVE_DESCRIPTOR_CD = 'C' –> se type 1   | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | DataBC                                      | 2023 (published 2024-02-27)           | Agriculture    | BC               | 2024-10-01       |
| Historical Fire Polygons                 | FIRE_YEAR >= 1964 (last 60 years)                                                                      | Apply filters <br> Calculate YEARS_SINCE <br> Merge inputs <br> Union with burn severity polygons <br> Identity with Forest Inventory Zones to identify coastal vs interior <br> Calculate PF_FACTOR_TIME <br> Calculate PF_FACTOR_SEVERITY based on coastal vs interior <br> Calculate PF_FACTOR = PF_FACTOR_TIME * PF_FACTOR_SEVERITY <br> Dissolve on PF_FACTOR <br> Split by PF_FACTOR <br> Union the split feature classes <br> Calculate MAX_PF_FACTOR <br> Dissolve on MAX_PF_FACTOR <br> Intersect with watersheds to calculate % watershed affected by fire = (affected area * pf_factor)/total watershed area                                                                                                                                                           | DataBC                                      | 2024-04-01                          | Fire           | BC               | 2024-09-30       |
| Current Fire Polygons                    | No filter                                                                                              | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | 2024-09-24                          | Fire           | BC               | 2024-09-30       |
| Fire History                             | FIRE_YEAR >= 1964 AND FIRE_YEAR < 9900 (last 60 years)                                                 | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2023                                 | Fire           | Yukon            | 2023-09-12       |
| Burn Severity Polygons                   | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | 2023-11-24                          | Fire           | BC               | 2024-09-30       |
| Forest Inventory Zones                   | FRST_NVNTE IN ('A', 'B', 'C') (coastal zones)                                                          | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | 2018-03-30                          | Fire           | BC               | 2024-10-01       |
| Harvested Areas in BC                    | HARVEST_YEAR >= 1964 (last 60 years)                                                                   | Apply filters <br> Calculate YEARS_SINCE_HARVEST <br> Merge inputs <br> Calculate PF_FACTOR <br> Erase reserves <br> Dissolve on PF_FACTOR <br> Split by PF_FACTOR <br> Union <br> Calculate MAX_PF_FACTOR <br> Dissolve on MAX_PF_FACTOR <br> Intersect with watersheds to calculate % watershed affected by forest harvest = (affected area * pf_factor)/total watershed area                                                                                                                                                                                                                                                                                                                      | DataBC                                      | 2023-10-24 (update published 11/4 but not available when I repulled data beginning of Oct) | Harvest        | BC               | 2024-02-08       |
| Forest Openings                          | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2021-07-06                          | Harvest        | Yukon            | 2023-09-06       |
| Historic Silviculture Inventory 50K      | HARVEST_START >= timestamp ‘1964-01-01 00:00:00’ (last 60 years)                                       | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2001-01-02                          | Harvest        | Yukon            | 2023-09-06       |
| Logging History on Haida Gwaii 1962-2021 | First_Harvest_Year >= 1964 OR Second_Harvest_Year >= 1964 (last 60 years)                              | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Gowgaia Institute                           | 2021                                 | Harvest        | Haida Gwaii      | 2021-11-09       |
| Results Inventory (for reserves)         | ((RES_CD IN ('G') and STK_ST_CD = 'MAT' and UPDATE_YR >= 2012) OR (RES_CD IN ('G') and STK_ST_CD = 'MAT' and RES_OBJ_CD = 'WTR') OR (RES_CD IN ('G') and STK_ST_CD in ('NP', 'MAT','IMM','RES') and STK_TP_CD in ('NAT', 'FOR', 'BR')) OR STK_ST_CD in ('L', 'M', 'R', 'S')) AND GEOM_YN = 'Y' | Apply filters <br> Dissolve                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | DataBC                                      | 2024-03-30                          | Harvest        | BC               | 2024-03-30       |
| Pest Infestation Polygons                | PEST_SEVERITY_CODE IN ('V', 'S', 'M') AND PEST_SPECIES_CODE NOT LIKE 'A%' AND PEST_SPECIES_CODE NOT LIKE 'N%' AND PEST_SPECIES_CODE NOT LIKE 'T%' AND PEST_SPECIES_CODE NOT LIKE 'V%' AND CAPTURE_YEAR >= 1964 (last 60 years) | 1. Apply filters <br> 2. Union with VRI dead layer <br> 3. Calculate YEARS_SINCE_PEST <br> 4. Calculate PF_FACTOR_TIME <br> 5. Calculate PF_STAND_PCT_DEAD (either from the midpoint of the severity mortality range or VRI stand_percentage_dead, whichever is greater) <br> 6. Calculate PF_FACTOR_SEVERITY (if severity is moderate = 0.5; if severity is severe or very severe = 1) <br> 7. Calculate PF_FACTOR = PF_FACTOR_TIME * PF_FACTOR_SEVERITY * PF_STAND_PCT_DEAD/100 <br> 8. Count overlapping features (produces a feature class of non-overlapping features with new objectid of output feature (non-overlapping) and a count of how many features overlapped. And produces an overlaps table: a lookup of the new (non-overlapping) feature objectids (OVERLAP_OID) with the original objectids of the overlapping features (ORIG_OID)) <br> 9. Join overlapping features (step 7) to the overlaps table (step 8) on [overlappingfeatures].objectid = [overlapstable].ORIG_OID <br> 10. Summarize MAX_PF_FACTOR by case field OVERLAP_OID (for each overlapping feature, identify the max PF_FACTOR) <br> 11. Join the MAX_PF_FACTOR back to the planarized (non-overlapping features): [non-overlapping features].OBJECTID = [summarytable].OVERLAP_OID <br> 12. Output is non-overlapping features with the max PF_FACTOR that occurred among the overlaps <br> 13. Intersect with watersheds to calculate % watershed affected by insect damage = (affected area * pf_factor)/total watershed area | DataBC                                      | 2022 (from CAPTURE_YEAR)             | Insects        | BC               | 2024-10-01       |
| Forest Health Overview                   | SEVERITY_CODE IN ('V', 'VS') AND DISTURBANCE_CODE NOT LIKE 'A%' AND DISTURBANCE_CODE NOT LIKE 'N%' AND DISTURBANCE_CODE NOT LIKE 'T%' AND DISTURBANCE_CODE NOT LIKE 'V%' AND SURVEY_YEAR >= 1964 (last 60 years) | Same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | GeoYukon                                    | 2022                                 | Insects        | Yukon            | 2024-03-04       |
| VRI Dead Layer                           | EARLIEST_NONLOGGING_DIST_TYPE LIKE 'I%' AND EARLIEST_NONLOGGING_DIST_DATE IS NOT NULL (select polygons disturbed by insects and with a disturbance date specified)  | Stand percentage dead used where greater than the midpoint of the severity rating range (from pest infestation polygons layer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | DataBC                                      | 2023 (published 2024-02-27)           | Insects        | BC               | 2024-10-01       |
| Minfile Inventory Database  MINFIL_MINERAL_FILE\MINFILE_point.shp              | STATUS_DS IN ('Developed Prospect', 'Producer', 'Past Producer')  | Apply filters <br> Add and calculate standardized fields: se_source, se_type, commodity_d, names, status_d <br> Append BC points into one feature class <br> Convert Yukon polygons to points (inside = true) <br> Append Yukon gravel point points with step 3 output <br> Append BC points (step 3) with Yukon points (step 5) <br> Intersect with watersheds to calculate number of mines per km2 = number of mines/total watershed area                                                                                                                                                                                                                                                                                                                                                             | DataBC                                      | 2024-02-12                          | Mines          | BC               | 2024-02-21       |
| Minfile Production Database MINFIL_PRODUCT\MINFL_PROD_point.shp                | Spatial selection – features that do not intersect selected features from inventory dataset (row above)                                                                   | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | DataBC                                      | 2021                                 | Mines          | BC               | 2024-02-21       |
| BC Aggregate Inventory Private Pits      | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | British Columbia Geological Survey MapPlace | 2004                                 | Mines          | BC               | 2012             |
| Quartz Land Use Permits 50K              | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2024-02-22                          | Mines          | Yukon            | 2024-04-06       |
| Quartz Mining Licences 50K               | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2013-09-20                          | Mines          | Yukon            | 2024-04-06       |
| Quartz Leases 50K                        | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2012-08-27                          | Mines          | Yukon            | 2024-04-06       |
| Mineral Claims Polygon Surveyed          | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2017-04-24                          | Mines          | Yukon            | 2024-04-06       |
| Coal Leases 50K                          | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2017-04-18                          | Mines          | Yukon            | 2024-04-06       |
| Coal Exploration Licenses 50K            | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2022-11-23                          | Mines          | Yukon            | 2024-04-06       |
| Gravel Pits 25K                          | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | GeoYukon                                    | 2023-09-16                          | Mines          | Yukon            | 2024-04-06       |
| BC CEF Integrated Roads                  | N/A                                                                                                    | Pairwise dissolve BC roads <br> Buffer Yukon road network by 30m <br> Erase forest resource roads that are within the 30m buffers <br> Merge Yukon road network with output of step 3 <br> Erase BC from step 4 (some Yukon roads overlap with BC) <br> Pairwise dissolve step 5 <br> Merge YT (step 6) with BC dissolved roads (step 1) <br> Intersect with watersheds to calculate length (km) of roads per km2 = length of roads/total watershed area                                                                                                                                                                                                                                                                                                                                   | DataBC                                      | Aug 2021                             | Roads          | BC               | 2023-09-06       |
| Yukon Road Network                       | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2022-03-08                          | Roads          | Yukon            | 2023-09-12       |
| Forestry Resource Roads 50K              | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2021-09-20                          | Roads          | Yukon            | 2023-09-12       |
| BC CEF Human Disturbance OGC_Geophysical_1_SLU_raw                 |   N/A                                                                            | Add and calculate standardized fields: <br> DISTRB_CD <br> DISTRB_GRP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance OGC_Infrastructure_1_SLU_raw                 |  N/A                                                                          | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Power_1_Dams_raw                |   N/A                                                                                     | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Power_2_Transmission_Lines_GBA_raw                |  N/A                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Rail_and_Infrastructure_1_Railways_GBA_raw                | N/A                                                             | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Rail_and_Infrastructure_2_Railways_GBA_NEBC_raw                |   N/A                                                      | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Rail_and_Infrastructure_3_VRI_Airports_raw                |  N/A                                                            | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance ROW_1_Surveyed_raw                |  N/A                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance ROW_2_Crown_raw                |   N/A                                                                                      | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Urban_1_BTM_raw                |   N/A                                                                                      | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| BC CEF Human Disturbance Urban_2_VRI_raw                |    N/A                                                                                     | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | DataBC                                      | Aug 2021                             | Urban & Industrial | BC               | 2023-09-06       |
| Landcover circa 2000                     | COVTYPE = 34 Urban                                                                                     | Apply filters <br> Merge YEC_Power_Lines, YEC_Power_Distribution_Lines, Utilities_Line_50k (Transmission line) <br> Buffer step 2 power lines by 12.5m then dissolve -> power lines <br> Merge pipeline_1 and Utilities_Line_50K (pipeline) <br> Buffer step 4 pipelines by 25m then dissolve -> oil and gas infrastructure <br> Buffer track_segment_1 by 10m then merge with runways_25k and dissolve -> rail and airport <br> Merge rail and airport (step 6), oil and gas infrastructure (step 5), power lines (step 3) with urban (LCC landcover) <br> Add and calculate standardized fields: DISTRB_CD, DISTRB_GRP | Government of Canada                        | 2000s                                | Urban & Industrial | Yukon            | N/A              |
| Utilities_Line_50k                       | "FEATURE" = 'Transmission line' <br> "FEATURE" = 'pipeline'                                           | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2004-06-14                          | Urban & Industrial | Yukon            | 2023-09-12       |
| YEC_Power_Lines                          | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | GeoYukon                                    | 2021-01-13                          | Urban & Industrial | Yukon            | 2023-09-12       |
| YEC_Power_Distribution_Lines             | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2021-01-13                          | Urban & Industrial | Yukon            | 2023-09-12       |
| Railroads_50K_Canvec canvec_50K_YT_Transport.gdb\track_segment_1                    |  N/A                                                             | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2017                                 | Urban & Industrial | Yukon            | 2023-09-12       |
| Runways_25k                              | N/A                                                                                                    | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | GeoYukon                                    | 2023-09-16                          | Urban & Industrial | Yukon            | 2023-09-19       |
| Canvec Pipelines 50K canvec_50K_YT_Res_MGT.gdb\pipeline_1                     |      N/A                                                                | same as above                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Natural Resources Canada                    | 2019-07-24                          | Urban & Industrial | Yukon            | 2023-09-12       |

